---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Alex Albright
#jobtitle: "Federal Reserve Bank of Minneapolis"
#address: "Federal Reserve Bank of Minneapolis, 90 Hennepin Ave, Minneapolis, MN 55401"
#fontawesome: no
web: albrightalex.com
email: alex@albrightalex.com
#github: apalbright
#twitter: allbriteallday
updated: yes

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: black
urlcolor: blue
---

# Employment

- *Research Economist*, Federal Reserve Bank of Minneapolis \hfill September 2022-\newline
Opportunity and Inclusive Growth Institute

- *Research Fellow*, Stanford Law School \hfill 2014-2016

# Education

- *Ph.D. in Economics*, Harvard University \hfill 2022
- *A.M. in Economics*, Harvard University  \hfill 2019
- *B.A. in Mathematics and Economics with Highest Honors*, Williams College \hfill 2014

# Working Papers 

- "No Money Bail No Problems? Evidence from Kentucky's Automatic Release Program"

- "The Hidden Effects of Algorithmic Recommendations"

- "After The Burning: The Economic Effects of the 1921 Tulsa Race Massacre" *(with Jeremy Cook, James Feigenbaum, Laura Kincaide, Jason Long, and Nathan Nunn)*

- "Uncorking Expert Reviews with Social Media: A Case Study Served with Wine" *(with Peter Pedroni and Steven Sheppard)*

<!-- # Research Interests -->

<!-- - Labor Economics, Criminal Legal System, Law and Economics, Inequality, Economic History -->

# Awards, Grants, Fellowships

- Abrams Family Economics Dissertation Fellowship (Harvard) \hfill 2022
- Irving Louis Horowitz Award *(most outstanding dissertation project)* \hfill 2021
- Horowitz Foundation Dissertation Prize \hfill 2021
- James M. and Cathleen D. Stone Ph.D. Scholar (Harvard Kennedy School) \hfill 2018-22
- Certificate of Distinction in Teaching *(4 times)* (Harvard) \hfill 2018-21
- Law and Economics Fellows Writing Prize (Harvard Law) \hfill 2019
- Terence M. Considine Fellow in Law and Economics (Harvard Law) \hfill 2018-21 
- Foundations of Human Behavior Grant (with James Feigenbaum & Nathan Nunn) \hfill 2019
- Inequality in America Grant (with James Feigenbaum & Nathan Nunn) \hfill 2019 
- Bradley Foundation Research Grant \hfill 2019
- Christophe Baron Prize (American Association of Wine Economists) \hfill 2016
- Best Lightning Talk Presenter (Oxford Connected Life Conference) \hfill 2015
- Carl Van Duyne Prize in Economics *(top thesis prize)* (Williams College) \hfill 2014

<!-- Gold Medalist, New York City Math Fair \hfill 2008 -->
<!-- - Research Scholarship, American Association of Wine Economists \hfill 2018 -->
<!-- - Phi Beta Kappa, Williams College \hfill 2014 -->
<!-- - Economics Highest Honors, Williams College \hfill 2014 -->
<!-- - Economics Department Class of 1960 Scholar, Williams College \hfill 2013 - 2014 -->
<!-- - National Merit Finalist \hfill 2010 -->
<!-- -  -->
<!-- - J-PAL Criminal Justice Reform Proposal Development Grant *(w/ Alley Edlebi)* \hfill 2019 - 2020 -->
<!-- - Summer Research and Travel Award, Harvard University \hfill 2018 -->
<!-- - Graduate Fellowship, Harvard University \hfill 2016 - Present -->

# Professional Activities

## Invited Seminars

- *2023 (including scheduled)*: Williams College, St. Olaf College, Clemson University, São Paulo School of Economis from Fundação Getulio Vargas (FGV-SP), Pontifical Catholic University of Rio de Janeiro (PUC-Rio), Insper (São Paulo)

- *2022*: Louisiana State University, Macalester College, London School of Economics, Federal Reserve Bank of Minneapolis, Consumer Financial Protection Bureau, Rutgers University, Department of Justice, RAND, Mathematica

- *2021*: Vancouver School of Economics

- *2020*: Economics of Crime Online Seminar Series

## Conference Presentations

- *2023 (including scheduled)*: Texas Economics of Crime Workshop *(discussant)* (UT Austin), Workshop on the Economics of Crime for Junior Scholars (Northeastern), Women in Federal Reserve System Economic Research Conference (Kansas City Fed), Society of Labor Economists’ Annual Meeting (SOLE), Women in Empirical Microeconomics Conference (University of Chicago)

- *2022*: NBER Summer Institute (Crime Session)

- *2021*: NBER Decentralization Conference *(discussant)*, ACM Conference on Equity and Access in Algorithms, Mechanisms, and Optimization (EAAMO), Workshop on the Economics of Crime for Junior Scholars 

- *2020*: Southern Economic Association Annual Conference (SEA), Annual Meeting of the American Law and Economics Association (ALEA) *(canceled due to Covid-19)*

- *2019:* Eighth Meeting for the Society for the Study of Economic Inequality (Paris School of Economics)

- *2015-18:* American Association of Wine Economists Conference (Cornell University), American Association of Wine Economists Conference (Université de Bordeaux), Connected Life Conference (Oxford University)

## Invited Guest Lectures

- *2023*: Dr. Shawn Bushway's "Economics of Crime" Winter Study Course at Williams College, Professor Sebastian Tello-Trillo's "Causal Inference" Course at University of Virginia

- *2022*: Professor Amanda Agan's "Evidence-Based Crime Policy" Course at Rutgers University 

- *2021*: Professor Louis Kaplow and Steve Shavell's "Law and Economics" Course at Harvard Law 

- *2019*: Harvard Government Department's "Data" Course (2 times), Professor Louis Kaplow and Steve Shavell's "Law and Economics" Course at Harvard Law 

## Press Coverage

- *2021*: The New York Times, CNN, TIME Magazine, CNBC, NBER Digest, Black Enterprise, The Root, Business Insider

- *2019*: WIRED, Axios

## Policy Talks

- *2022*: Niskanen Center Webinar Series on Prosecution Reform (2 times)

- *2020*: Judicial Council of California Seminar

## Podcast Interviews

- *2022*: Probable Causation (host: Jennifer Doleac)

# Professional Service

## Referee Service

- *Quarterly Journal of Economics, Review of Economics and Statistics, Journal of Urban Economics, Journal of Policy Analysis and Management, Journal of Empirical Legal Studies, Review of Economics and Statistics: Short Papers, Journal of Urban Economics: Insights*

## Conference and Seminar Service

- Program Committee Member, FAccT  \hfill 2023
- (ACM Conference on Fairness, Accountability and Transparency) 
-
- Co-Organizer, "Heterogeneity by Gender: Evidence from Job Market Papers" \hfill 2020
- (with Stephanie Kestelman; Harvard Economics Seminar Event) 


## Community Service

- Panelist, UBC Women in Economics Job Market Event \hfill 2022
- Founding Member, Harvard Graduate Women in Economics \hfill 2017-21
- Master of Ceremonies, Harvard Economics Holiday Party \hfill 2018 & 2020
- Invited Speaker, R-Ladies Boston \hfill 2018
- Peer Mentor, Harvard Economics Department \hfill 2017-18

# Teaching 

- *Seminar Leader*, Undergraduate Thesis Writer Seminar, Harvard Economics \hfill 2020-21
- *Seminar Leader*, Undergraduate Thesis Writer Seminar, Harvard Economics \hfill 2018-19
- *Teaching Assistant*, Empirical Debates in Law and Policy, Stanford Law School \hfill  2014

# Publications Outside Economics

## Data Journalism

- "We analyzed every 'Modern Love' column from the past 10 years. Here's what we learned about love" (with Emma Pierson). Quartz. 2017.

- "Which U.S. State Performs Best in the New Yorker Caption Contest?" (with Bob Mankoff). The New Yorker. 2015.

## Conference Proceedings

- "One Size Does Not Fit All: The Shortcomings of the Mainstream Data Scientist Working for Social Good" (with Sarah Levine). Proceedings of the Bloomberg Data for Good Exchange. 2015.